name: Release

on:
    push:
        branches:
            - 'main'

permissions: {}
jobs:
    release:
        # prevents this action from running on forks
        if: github.repository == 'gyurielf/ci-test'
        permissions:
            contents: write # to create release (changesets/action)
            pull-requests: write # to create pull request (changesets/action)
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                  # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
                  fetch-depth: 0

            - name: Setup Node.js 18.15
              uses: actions/setup-node@v3
              with:
                  node-version: 18.15

            - name: Install dependencies
              run: npm install --frozen-lockfile --prefer-offline --ignore-scripts

            # - name: Packaging
            #   run: |
            #       npm run package

            - name: Create Dist
              run: |
                  mkdir dist
                  cp package.json dist
                  touch index.js
                  cat << EOF > "index.js"
                    export default { console.log('hey') }
                  EOF                 
                  mv index.js dist
                  ls -l

            - name: Creating .npmrc
              run: |
                  cat << EOF > "$HOME/.npmrc"
                    //registry.npmjs.org/:_authToken=$NPM_TOKEN
                  EOF
                  cp $HOME/.npmrc dist                                   
                  ls -l
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  # This expects you to have a script called release which does a build for your packages and calls changeset publish
                  publish: npm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
