name: Release

on:
    push:
        branches:
            - 'main'

jobs:
    release:
        # prevents this action from running on forks
        if: github.repository == 'gyurielf/ci-test'
        permissions:
            contents: write # to create release (changesets/action)
            pull-requests: write # to create pull request (changesets/action)
        name: Release
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                # pseudo-matrix for convenience, NEVER use more than a single combination
                node: [18.15]
                os: [ubuntu-latest]
        steps:
            - name: checkout
              uses: actions/checkout@v3
              with:
                  # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
            - name: Install dependencies
              run: npm install --frozen-lockfile --prefer-offline --ignore-scripts
            - name: Packaging aka build
              run: |
                  npm run package
            - name: Creating .npmrc
              run: |
                  cat << EOF > "$HOME/.npmrc"
                    //registry.npmjs.org/:_authToken=$NPM_TOKEN
                  EOF
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  # This expects you to have a script called release which does a build for your packages and calls changeset publish
                  publish: npm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
